config/routes.rb
Rails.application.routes.draw do

  # User authentication routes
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # Routes for portfolios
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'cricket-tips-portfolios', to: 'portfolios#crickettipsshow'



  # Other routes
  get 'abouts', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # Routes for home
  get 'home/about/aboutme', to: 'home#about'
  get 'home/contact'

  # Root route
  root to: 'pages#about'
  # Routes for blogs
  get 'blogs', to: 'blogs#index'
  get 'blog/:id', to: 'blogs#show', as: 'blog_show'
  get 'blogs/new', to: 'blogs#new', as: 'new_blog'
  get 'blog/:id/edit', to: 'blogs#edit', as: 'edit_blog'
  post 'blogs', to: 'blogs#create'
  patch 'blog/:id', to: 'blogs#update', as: 'blog'
  delete 'blog/:id', to: 'blogs#destroy', as: 'destroy_blog'
end

# resources :blogs do
#   member do
#     get :toggle_status
#   end
# end
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# Defines the root path route ("/")
# root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title, :body

  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  # includes in some of the helper files to act as concern
  # concerns make modules that can be used across models
  # Modules are collections of methods and constants. They cannot generate instances, like classes.
  extend ActiveSupport::Concern
  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  includes Placeholder
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda { |attributes| attributes['name'].blank? }
  validates_presence_of :title, :subtitle, :body, :thumb_image

  # def self.crickettips
  #   where(subtitle: "Cricket Tips")
  # end

  # custom scopes for specific items to be popped up on index page instead of Portfolio.all, you can say Portfolio.crickettips
  scope :cricketTips, -> { where(subtitle: "Cricket Tips") }

  #set default values:
  after_initialize  :set_defaults

  def set_defaults
    self.thumb_image ||= Placeholder.image_generator(height:'200',width:'100')
    self.main_image ||= Placeholder.image_generator(height:'300',width:'200')
  end

  # '||=' operator is a short-cut to check if the value is nill, then replace, or else not.
  # other way of setting defaults is basically through db/schema and go there and write defaul: "sadfsdf", infront of the value.
end

app/models/skill.rb
class Skill < ApplicationRecord
  includes Placeholder
  after_initialize :set_defaults

  def set_defaults
    badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title, presence: true
  has_many :blog
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,  :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhiteList
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_show_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_show_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/DeviseWhiteList.rb
module DeviseWhiteList
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @post = Blog.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index
    @portfolio_items = Portfolio.all
  end

  def crickettipsshow
    @cricket_tips = Portfolio.cricketTips
    respond_to do |format|
      format.html # Render crickettipsshow.html.erb by default
    end
  end

  def new
    @portfolio_items = Portfolio.new
    #hardcoded version of running nested attributes
    # 3.time {@portfolio_items.tecnologies.build}
  end
  def show
    @portfolio_items = Portfolio.find(params[:id])
  end
  def edit
    @portfolio_items = Portfolio.find(params[:id])

  end
  def create
    @portfolio_items = Portfolio.new( params.require(:portfolio).permit(:title, :subtitle)) #, :body, technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully created." }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  def update
    @portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    #look-up
    @portfolio_item = Portfolio.find(params[:id])
    #for deleting that item
    @portfolio_item.destroy
    respond_to do |format|
        format.html {redirect_to portfolios_path, notice: 'The record was successfully destroyed.'}
    end
  end

  private
  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p>
    <strong>Title:</strong>
    <%= blog.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= blog.body %>
  </p>

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: @blog) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", blog_show_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog_show_path(blog) %>
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %>
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", destroy_blog_path(@blog), method: :delete %>
</div>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<html>
  <head>
    <title>DevcampPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if current_user %>
    <%= button_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Register", new_user_registration_path %>
    <%= button_to "Login", new_user_session_path %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/portfolios/crickettips.html.erb
<p style="color: green"><%= notice %></p>

<h1>Portfolio Items</h1>
<%= link_to "Create New Item", new_portfolio_path %>

<div>
  <% @cricket_tips.each do |portfolio_item| %>
    <%= link_to portfolio_item.title, portfolios_show_path(portfolio_item.id) %>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit Item", edit_portfolio_path(portfolio_item.id) %>
    <%= button_to 'Delete Portfolio Item',portfolio_path(portfolio_item), method: :delete %>

  <% end %>
</div>

app/views/portfolios/edit.html.erb
<%= form_with(model: @portfolio_items) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Portfolio Items</h1>
<%= link_to "Create New Item", new_portfolio_path %>

<div>
  <% @portfolio_items.each do |portfolio_item| %>
    <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit Item", edit_portfolio_path(portfolio_item.id) %>
    <%= button_to 'Delete Portfolio Item',portfolio_path(portfolio_item), method: :delete %>

<% end %>
</div>

app/views/portfolios/new.html.erb
<%= form_with(model: @portfolio_items) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :subtitle, style: "display: block" %>
    <%= form.text_field :subtitle %>
  </div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<h1>Show Page</h1>

  <p><%=  @portfolio_items.title %></p>
  <p><%=  @portfolio_items.subtitle %></p>
  <p><%=  @portfolio_items.body %></p>
  <%= image_tag  @portfolio_items.thumb_image unless  @portfolio_items.thumb_image.nil? %>

<%= link_to "Edit Item", edit_portfolio_path(@portfolio_items.id) %>
<%= button_to 'Delete Portfolio Item',@portfolio_item, method: :delete %>